name: Node.js CI

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18 >=18.1
    - run: |
        npm install
        npm run lint

  test:

    name: test (on ${{ matrix.runs-on }})

    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18 >=18.1
    - run: |
        npm install
        npm run make-fixtures
        npm test
