name: Node.js CI

on: [push, pull_request]

jobs:

  lint:

    name: Lint Files

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ^20.3
    - run: |
        npm install
        npm run lint

  test:

    name: Test (Node.js ${{ matrix.node-version }} on ${{ matrix.runs-on }})

    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        node-version: [^20.3]
        runs-on: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm run make-fixtures
        npm test
